# Generated by Django 5.0.1 on 2024-02-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nickname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_apellido', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.genero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaReproduccion.usuario')),
            ],
        ),
    ]
