create database bd_lista_mois;

CREATE TABLE USUARIO(
    NICKNAME VARCHAR(20), 
    NOMBRE_APELLIDO VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL, 
    PASSWORD VARCHAR(10) NOT NULL,
    PRIMARY KEY(NICKNAME) 

); 

--TABLA GENERO 
CREATE TABLE GENERO(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
); 

-- TABLA CANCION 
CREATE TABLE CANCION(
    ID INT AUTO_INCREMENT,
    NOMBRE VARCHAR(100),
    AUTOR VARCHAR(100),
    NICKNAME VARCHAR(20),
    GENERO_ID INT,
    PRIMARY KEY(ID)

);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_usuario 
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

ALTER TABLE CANCION ADD CONSTRAINT fk_cancion_genero 
FOREIN KEY(GENERO_ID) REFERENCES GENERO(ID); 

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    NICKNAME VARCHAR(20),
    PRIMARY KEY(ID)
); 

ALTER TABLE LISTA_REPRODUCCION ADD CONSTRAINT fk_lista_usuario 
FOREIGN KEY(NICKNAME) REFERENCES USUARIO(NICKNAME);

-- TABLA LISTA_CANCION 
CREATE TABLE LISTA_CANCION(
    LISTA_ID INT, 
    CANCION_ID INT 
); 

ALTER TABLE LISTA_CANCION ADD CONSTRAINT pk_lista_cancion 
PRIMARY KEY(LISTA_ID, CANCION_ID); 

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_listar
FOREIGN KEY(LISTA_ID) REFERENCES LISTA_REPROCCION(ID); 

ALTER TABLE LISTA_CANCION ADD CONSTRAINT fk_listac_cancion 
FOREIGN KEY(CANCION_ID) REFERENCES CANCIION(ID);


--INSERT insert into USUARIO values("rut", "rut at", "r@t.com", "12345");

insert into USUARIO (nickname,password,nombre_apellido,email) 
values("isaac", "12345", "isaac at", "is@a.com");

--UPDATE 
update USUARIO
set password = "1111" where nickname = "isaac";

--INSERT 
insert into GENERO values(default, ROCK);--1
insert into GENERO values(default, ROCK PARAGUAYO);--2
insert into GENERO(descripcion) values("TRAP");
insert into CANCION values(default, "Tanto y nada", "Flou", "rut", 1);


